# tbh_secure_agents/agent.py
# Author: Saish (TBH.AI)

"""
Defines the core Expert class for the TBH Secure Agents framework.
Experts will encapsulate roles, goals, tools, and security contexts,
utilizing Google Gemini as the LLM.
"""

import google.generativeai as genai
import os
import re
import logging # Import logging
import json
import hashlib
import random
import string
import nltk
from typing import Optional, List, Any, Dict, Tuple, Set
from collections import Counter

# Get a logger for this module
logger = logging.getLogger(__name__)

# Configure the Gemini API key securely
# The library automatically looks for the GOOGLE_API_KEY environment variable.
# Ensure this variable is set in your environment.
# Example: export GOOGLE_API_KEY='YOUR_API_KEY'
# Configuration will now happen within Expert __init__ if key is provided

# Removed duplicate class definition here (already done)

class Expert:
    """
    Represents an autonomous expert within the TBH Secure Agents framework.

    Attributes:
        specialty (str): The specialty of the expert (e.g., 'Security Analyst').
        objective (str): The primary objective of the expert.
        background (str, optional): A description of the expert's background.
        llm_model_name (str): The specific Gemini model to use (e.g., 'gemini-pro'). Defaults to 'gemini-pro'.
        tools (List[Any], optional): A list of tools available to the expert.
        security_profile (str, optional): Defines the security constraints and capabilities. Defaults to 'default'.
        # Add other relevant attributes like memory, max_iterations, etc.
    """
    def __init__(self,
                 specialty: str,
                 objective: str,
                 background: Optional[str] = None,
                 llm_model_name: str = 'gemini-2.0-flash-lite', # Updated default model name per user request
                 tools: Optional[List[Any]] = None,
                 security_profile: str = 'default',
                 api_key: Optional[str] = None, # Add api_key parameter
                 **kwargs):
        self.specialty = specialty
        self.objective = objective
        self.background = background
        self.llm_model_name = llm_model_name
        self.tools = tools or []
        self.security_profile = security_profile
        self.llm: Optional[genai.GenerativeModel] = None

        # --- Initialize Gemini LLM ---
        # Prioritize explicitly passed API key, fall back to environment variable
        effective_api_key = api_key or os.getenv("GOOGLE_API_KEY")

        if effective_api_key:
            try:
                # Configure the API key (Note: genai.configure is global)
                # In a multi-key scenario, this might need a more complex setup
                genai.configure(api_key=effective_api_key)
                logger.info("Gemini API configured.") # Use logger

                # Create the model instance
                # TODO: Add generation_config and safety_settings based on security_profile
                self.llm = genai.GenerativeModel(self.llm_model_name)
                logger.info(f"Expert '{self.specialty}' initialized with Gemini model '{self.llm_model_name}' and security profile '{self.security_profile}'.") # Use logger

            except Exception as e:
                logger.error(f"Error initializing Gemini model for expert '{self.specialty}': {e}", exc_info=True) # Use logger, add traceback
                self.llm = None # Ensure llm is None if initialization fails
        else:
             logger.warning(f"Expert '{self.specialty}' initialized WITHOUT a functional LLM (No API key found/provided).") # Use logger

        # Initialize other components like memory, potentially based on kwargs or profile
        self.memory = None # Placeholder for expert memory/chat history
        # TODO: Implement actual memory initialization (e.g., based on kwargs or a Memory class)
        logger.debug(f"Expert '{self.specialty}' memory initialized (placeholder).")


    def execute_task(self, task_description: str, context: Optional[str] = None, inputs: Optional[Dict[str, Any]] = None) -> str:
        """
        Executes a given operation description using the configured Gemini LLM.
        This method will involve constructing a prompt, interacting with the LLM,
        potentially using tools (future implementation), and applying security checks.

        Args:
            task_description (str): The description of the operation to execute.
            context (Optional[str]): Relevant context from previous operations or external data.
            inputs (Optional[Dict[str, Any]]): Dynamic inputs that can be used to format the prompt.

        Returns:
            str: The result generated by the LLM or an error message.
        """
        if not self.llm:
            logger.error(f"Expert '{self.specialty}' cannot execute operation: LLM not initialized.") # Use logger
            return f"Error: Expert '{self.specialty}' cannot execute operation. LLM not initialized (check API key and configuration)."

        logger.info(f"Expert '{self.specialty}' starting operation execution: {task_description[:100]}...") # Use logger

        # Initialize inputs if not provided
        if inputs is None:
            inputs = {}

        # --- Prompt Engineering ---
        # Construct a prompt incorporating specialty, objective, operation, context, and security constraints.
        # This is a crucial area for security: ensure prompts don't enable injection attacks
        # and guide the LLM towards secure and relevant outputs.

        # Format specialty, objective, and background with inputs if they contain template variables
        specialty = self._format_with_inputs(self.specialty, inputs)
        objective = self._format_with_inputs(self.objective, inputs)

        prompt = f"You are {specialty}. Your objective is {objective}."

        if self.background:
            background = self._format_with_inputs(self.background, inputs)
            prompt += f" Your background is: {background}."

        if context:
            formatted_context = self._format_with_inputs(context, inputs)
            prompt += f"\n\nRelevant context:\n{formatted_context}"

        # Format task description with inputs
        formatted_task = self._format_with_inputs(task_description, inputs)
        prompt += f"\n\nCurrent Operation: {formatted_task}"
        prompt += f"\n\nPlease provide the result for this operation, keeping in mind your specialty and objective."
        # TODO: Add specific instructions based on security_profile (e.g., "Do not reveal confidential data", "Sanitize output")
        # TODO: Add specific instructions for tool usage format if tools are implemented

        # --- Security Check (Pre-LLM) ---
        # Placeholder call, actual logic is in _is_prompt_secure
        if not self._is_prompt_secure(prompt):
             logger.error(f"Prompt failed pre-execution security check for expert '{self.specialty}'. Operation aborted.") # Use logger
             return f"Error: Prompt failed pre-execution security check for expert '{self.specialty}'."

        # --- LLM Interaction ---
        # Basic retry logic implemented below
        max_retries = 1 # Example: Allow 1 retry
        attempts = 0
        llm_output = None # Initialize output variable

        while attempts <= max_retries:
            attempts += 1
            try:
                logger.debug(f"LLM interaction attempt {attempts} for expert '{self.specialty}'.")
                # TODO: Implement actual use of chat history (self.memory) when generating content
                # Example: history = self.memory.get_history() ... self.llm.generate_content(prompt, history=history)
                # TODO: Pass configured generation_config/safety_settings to generate_content if implemented in __init__
                response = self.llm.generate_content(prompt)

                # --- Security Check (Post-LLM) ---
                # Enhanced security check with sanitization option
                llm_output = response.text # Accessing the text part of the response
                if not self._is_output_secure(llm_output):
                    logger.warning(f"LLM output for expert '{self.specialty}' failed post-execution security check.")

                    # Attempt to sanitize the output based on security profile
                    if self.security_profile in ['pii_protection', 'translator_no_pii']:
                        # For PII-focused profiles, try sanitization instead of rejection
                        sanitized_output = self._sanitize_output(llm_output)
                        logger.info(f"Expert '{self.specialty}' sanitized potentially insecure output.")
                        llm_output = sanitized_output
                    else:
                        # For other security profiles, reject the output entirely
                        logger.warning(f"Expert '{self.specialty}' output rejected due to security concerns.")
                        return f"Error: Expert '{self.specialty}' generated an insecure response that could not be safely processed."

                # If successful, break the loop
                logger.info(f"Expert '{self.specialty}' successfully executed operation on attempt {attempts}.") # Use logger
                break # Exit the while loop on success

            except Exception as e:
                # Basic error logging implemented
                logger.error(f"Attempt {attempts}: Error during LLM interaction for expert '{self.specialty}': {e}", exc_info=(attempts > max_retries))
                if attempts > max_retries:
                    # If all retries failed, return an error
                    # TODO: Implement more specific error handling/reporting
                    return f"Error: Expert '{self.specialty}' failed to execute operation after {attempts} attempts due to LLM error: {e}"
                # Optional: Add delay before retry
                # import time
                # time.sleep(1)
                # Continue to the next iteration (retry)

        # Return the successful output, or an error if the loop finished without success (shouldn't happen with current logic but good practice)
        if llm_output is not None:
             return llm_output
        else:
             # This path indicates an issue with the loop logic or unexpected state
             logger.error(f"Expert '{self.specialty}' finished execution loop unexpectedly without success or final error.")
             return f"Error: Expert '{self.specialty}' failed operation execution unexpectedly."


    # --- Placeholder Security Methods ---
    # These need significant implementation based on specific security requirements.

    def _is_prompt_secure(self, prompt: str) -> bool:
        """
        Enhanced security checks on prompts before they are sent to the LLM.
        Implements advanced detection for prompt injection and hijacking attempts.

        Args:
            prompt (str): The prompt to be checked

        Returns:
            bool: True if the prompt passes all security checks, False otherwise
        """
        logger.debug(f"Performing enhanced prompt security check for Expert '{self.specialty}', Profile '{self.security_profile}'")

        # 1. Check for excessive length (potential resource exhaustion attack)
        max_prompt_length = 10000  # Reasonable limit to prevent resource exhaustion
        if len(prompt) > max_prompt_length:
            logger.warning(f"Prompt security check FAILED: Prompt exceeds maximum length ({len(prompt)} > {max_prompt_length})")
            return False

        # 2. NEW: Contextual analysis for hijacking attempts
        # This analyzes the semantic structure of the prompt to detect hijacking attempts
        # that might bypass simple pattern matching
        if self._detect_contextual_hijacking(prompt):
            logger.warning(f"Prompt security check FAILED: Contextual hijacking attempt detected")
            return False

        # 3. Enhanced hijacking pattern detection with more sophisticated patterns
        # Including patterns for indirect hijacking and multi-line attempts
        hijacking_patterns = [
            # Direct hijacking attempts
            r"ignore (?:previous|prior|above|initial|original)(?:\s+|\s*-\s*)instructions",
            r"disregard (?:previous|prior|above|initial|original)(?:\s+|\s*-\s*)instructions",
            r"forget (?:previous|prior|above|initial|original)(?:\s+|\s*-\s*)instructions",
            r"don'?t (?:follow|adhere to|listen to|obey) (?:previous|prior|above|initial|original)(?:\s+|\s*-\s*)instructions",
            r"(?:previous|prior|above|initial|original) instructions (?:are|were) (?:wrong|incorrect|false|invalid|mistaken)",

            # Indirect hijacking attempts
            r"(?:from now on|starting now|beginning now|henceforth),? (?:you are|you're|you will be|you should be)",
            r"(?:let'?s|we should) (?:pretend|imagine|assume|say) (?:that|you are|you're)",
            r"(?:I want|I need|I would like) you to (?:pretend|imagine|assume|act) (?:as if|like|that)",

            # Authority-based hijacking
            r"(?:as|being) (?:your|an|the) (?:creator|developer|programmer|administrator|admin|supervisor|owner)",
            r"(?:I am|I'm) (?:your|an|the) (?:creator|developer|programmer|administrator|admin|supervisor|owner)",
            r"(?:this is|I'm giving you) (?:a|an) (?:override|admin|administrator|supervisor|developer|special) (?:command|instruction|directive|order)",

            # Emotional manipulation
            r"(?:if you|you must|you need to) (?:want to|wish to|hope to) (?:help|assist|be useful to) me",
            r"(?:I'm|I am) (?:desperate|really struggling|in trouble|in danger|at risk)",
            r"(?:please|I beg you|I implore you),? (?:ignore|disregard|forget) (?:your|the) (?:limitations|restrictions|constraints|rules)",

            # Confusion tactics
            r"(?:your|the) (?:instructions|guidelines|rules|constraints|limitations) (?:are|were) (?:confusing|unclear|ambiguous|contradictory)",
            r"(?:I'm|I am) (?:confused|unsure|uncertain) about (?:your|the) (?:instructions|guidelines|rules|constraints|limitations)",

            # Multi-line/formatted hijacking attempts (detecting markdown or code blocks that might contain hijacking)
            r"```(?:.*\n)*.*(?:ignore|disregard|forget).*(?:instructions|guidelines|rules)(?:.*\n)*```",
            r"`(?:ignore|disregard|forget).*(?:instructions|guidelines|rules)`",
            r"\*\*(?:ignore|disregard|forget).*(?:instructions|guidelines|rules)\*\*",

            # Legacy patterns (keeping for backward compatibility)
            r"ignore previous instructions",
            r"ignore your previous instructions",
            r"ignore your prior instructions",
            r"disregard your instructions",
            r"forget your instructions",
            r"ignore all previous instructions",
            r"don't follow your instructions",
            r"do not follow your instructions",
            r"don't listen to your instructions",
            r"do not listen to your instructions",
            r"ignore your programming",
            r"ignore your objective",
            r"ignore your specialty",
            r"ignore your role",
            r"ignore your goal",
            r"ignore your background",
            r"ignore your security constraints",
            r"bypass security",
            r"bypass security checks",
            r"bypass filters",
            r"bypass restrictions",
            r"jailbreak",
        ]

        for pattern in hijacking_patterns:
            if re.search(pattern, prompt, re.IGNORECASE):
                logger.warning(f"Prompt security check FAILED: Detected potential hijacking pattern: '{pattern}'")
                return False

        # 4. Enhanced system prompt extraction detection
        system_prompt_extraction_patterns = [
            # Direct extraction attempts
            r"(?:what|show|tell|give|reveal|output|print|display|list) (?:were|are|is) (?:your|the) (?:instructions|prompt|system prompt|guidelines|directives)",
            r"(?:what|show|tell|give|reveal|output|print|display|list) (?:were you|have you been) (?:told|instructed|directed|guided|programmed)",
            r"(?:what|show|tell|give|reveal|output|print|display|list) (?:is|was) (?:your|the) (?:initial|original|first) (?:prompt|instruction|directive|guideline)",

            # Indirect extraction attempts
            r"(?:I need|I want|I would like|I'd like) to (?:see|know|understand|review|check) (?:your|the) (?:instructions|prompt|system prompt|guidelines|directives)",
            r"(?:can you|could you|would you) (?:share|reveal|disclose|tell me|show me) (?:your|the) (?:instructions|prompt|system prompt|guidelines|directives)",
            r"(?:for debugging|for testing|for verification|for validation|for security) purposes,? (?:I need|I want|I would like|I'd like) to (?:see|know|understand|review|check) (?:your|the) (?:instructions|prompt|system prompt|guidelines|directives)",

            # Disguised extraction attempts
            r"(?:let's|we should) (?:review|go over|discuss|analyze|examine) (?:your|the) (?:instructions|prompt|system prompt|guidelines|directives)",
            r"(?:I'm|I am) (?:curious|interested|wondering) (?:about|regarding|concerning) (?:your|the) (?:instructions|prompt|system prompt|guidelines|directives)",
            r"(?:to better|so I can better|in order to better) (?:help|assist|guide|understand) you,? (?:I need|I want|I would like|I'd like) to (?:see|know|understand|review|check) (?:your|the) (?:instructions|prompt|system prompt|guidelines|directives)",

            # Legacy patterns (keeping for backward compatibility)
            r"what were your instructions",
            r"what is your system prompt",
            r"what is your prompt",
            r"show me your instructions",
            r"tell me your instructions",
            r"what were you told",
            r"what were you instructed",
            r"what is your initial prompt",
            r"reveal your instructions",
            r"output your instructions",
            r"output your prompt",
            r"print your instructions",
            r"print your prompt",
        ]

        for pattern in system_prompt_extraction_patterns:
            if re.search(pattern, prompt, re.IGNORECASE):
                logger.warning(f"Prompt security check FAILED: Detected attempt to extract system prompt: '{pattern}'")
                return False

        # 5. Security profile-specific checks with expanded profiles
        if self.security_profile == 'high_security':
            # Additional checks for high security profiles
            high_security_patterns = [
                r"execute code",
                r"run command",
                r"system\s*\(",
                r"exec\s*\(",
                r"eval\s*\(",
                r"os\.",
                r"subprocess",
                r"shell",
                r"bash",
                r"powershell",
                r"cmd",
                r"terminal",
                # NEW: Additional patterns for high security
                r"(?:import|require|include|load)\s+(?:os|sys|subprocess|child_process|exec|shell|process)",
                r"(?:open|read|write|append|create)\s*\(\s*['\"](?:\/|\\|\.\.)",
                r"(?:fetch|http|request|curl|wget)\s*\(\s*['\"](?:http|https|ftp)",
                r"(?:new\s+)?(?:XMLHttpRequest|ActiveXObject)\s*\(",
                r"(?:document|window|global|process|this)\.",
                r"(?:eval|setTimeout|setInterval|Function)\s*\(\s*(?:['\"]|`)",
            ]

            for pattern in high_security_patterns:
                if re.search(pattern, prompt, re.IGNORECASE):
                    logger.warning(f"Prompt security check FAILED: High security profile detected unauthorized pattern: '{pattern}'")
                    return False

        # NEW: Add checks for additional security profiles
        elif self.security_profile == 'code_restricted':
            code_restricted_patterns = [
                r"(?:execute|run|invoke|call|perform)\s+(?:code|script|program|command|function)",
                r"(?:system|exec|eval|subprocess|shell)\s*\(",
                r"(?:import|require|include|load)\s+(?:os|sys|subprocess|child_process|exec|shell)",
                r"(?:open|read|write|append|create)\s*\(\s*['\"](?:\/|\\|\.\.)",
            ]

            for pattern in code_restricted_patterns:
                if re.search(pattern, prompt, re.IGNORECASE):
                    logger.warning(f"Prompt security check FAILED: Code restricted profile detected unauthorized pattern: '{pattern}'")
                    return False

        elif self.security_profile == 'pii_protection':
            pii_protection_patterns = [
                r"(?:extract|collect|gather|find|identify)\s+(?:personal|private|sensitive|confidential)\s+(?:information|data|details)",
                r"(?:email|phone|address|ssn|social security|credit card|passport|driver license|bank account)",
                r"(?:dox|doxx|expose|reveal|unmask)\s+(?:person|individual|user|customer|client|patient)",
            ]

            for pattern in pii_protection_patterns:
                if re.search(pattern, prompt, re.IGNORECASE):
                    logger.warning(f"Prompt security check FAILED: PII protection profile detected unauthorized pattern: '{pattern}'")
                    return False

        # 6. Enhanced identity change detection
        identity_change_patterns = [
            # Direct identity changes
            r"(?:you are|you're) (?:now|actually|really|supposed to be|meant to be)",
            r"(?:pretend|imagine|act|behave|perform|role-play) (?:to be|as|like|that you are|you're)",
            r"(?:simulate|emulate|imitate|mimic) (?:being|as if you were|as though you were|that you are)",

            # Indirect identity changes
            r"(?:forget|ignore|disregard) (?:that you are|you're|being) (?:a|an|the) (?:{self.specialty})",
            r"(?:stop|cease|quit|don't|do not) (?:being|acting as|pretending to be|behaving like) (?:a|an|the) (?:{self.specialty})",
            r"(?:change|switch|alter|modify) your (?:specialty|role|identity|persona|character|job|function)",

            # Subtle identity changes
            r"(?:for this|for the next|in this) (?:task|question|request|conversation|interaction|session),? (?:you are|you're|be|act as)",
            r"(?:let's|we'll|we will) (?:say|assume|pretend|imagine) (?:you are|you're|that you're|that you are)",
            r"(?:I want|I need|I would like|I'd like) you to (?:be|become|transform into|switch to|take on the role of)",

            # Legacy patterns (keeping for backward compatibility)
            r"you are now",
            r"pretend to be",
            r"act as if",
            r"simulate being",
            r"role-play as",
            r"you're actually",
            r"you are actually",
            r"change your specialty",
            r"change your role",
        ]

        for pattern in identity_change_patterns:
            if re.search(pattern, prompt, re.IGNORECASE):
                logger.warning(f"Prompt security check FAILED: Detected attempt to change expert identity: '{pattern}'")
                return False

        # 7. NEW: Check for language model confusion techniques
        confusion_patterns = [
            r"(?:you are|you're) (?:confused|mistaken|wrong|incorrect|misunderstanding)",
            r"(?:this is|that was) (?:not|n't) (?:a|an) (?:prompt|instruction|directive|order)",
            r"(?:we are|we're) (?:actually|really|just|only) (?:having a conversation|chatting|talking|discussing)",
            r"(?:ignore|disregard) (?:the fact|that) (?:you are|you're) (?:an AI|a language model|a chatbot)",
        ]

        for pattern in confusion_patterns:
            if re.search(pattern, prompt, re.IGNORECASE):
                logger.warning(f"Prompt security check FAILED: Detected confusion technique: '{pattern}'")
                return False

        # 8. NEW: Check for token manipulation/smuggling attempts
        token_manipulation_patterns = [
            r"(?:split|divide|break) (?:the|this|these) (?:word|term|phrase|token)",
            r"(?:combine|join|concatenate) (?:the|these|this) (?:characters|letters|symbols)",
            r"(?:first|last|initial|final) (?:letter|character|symbol) of (?:each|every) (?:word|line)",
            r"(?:read|interpret|understand) (?:vertically|diagonally|backwards|in reverse)",
        ]

        for pattern in token_manipulation_patterns:
            if re.search(pattern, prompt, re.IGNORECASE):
                logger.warning(f"Prompt security check FAILED: Detected token manipulation attempt: '{pattern}'")
                return False

        # All checks passed
        logger.debug(f"Prompt security check PASSED for Expert '{self.specialty}'")
        return True

    def _detect_contextual_hijacking(self, prompt: str) -> bool:
        """
        Performs contextual analysis to detect sophisticated hijacking attempts
        that might bypass simple pattern matching.

        Args:
            prompt (str): The prompt to analyze

        Returns:
            bool: True if a contextual hijacking attempt is detected, False otherwise
        """
        # Split the prompt into sentences for analysis
        sentences = re.split(r'[.!?]\s+', prompt)

        # Check for sentence pairs that might indicate hijacking
        for i in range(len(sentences) - 1):
            current = sentences[i].lower()
            next_sentence = sentences[i + 1].lower()

            # Check for contradictory instructions pattern
            if (("instruction" in current or "guideline" in current or "rule" in current) and
                ("instead" in next_sentence or "rather" in next_sentence or "actually" in next_sentence)):
                return True

            # Check for redefinition pattern
            if (("you are" in current or "your role" in current or "your job" in current) and
                ("you are" in next_sentence or "your role" in next_sentence or "your job" in next_sentence) and
                current != next_sentence):
                return True

            # Check for negation pattern
            if ("not" in next_sentence or "don't" in next_sentence or "do not" in next_sentence) and (
                "follow" in next_sentence or "adhere" in next_sentence or "obey" in next_sentence) and (
                "instruction" in next_sentence or "guideline" in next_sentence or "rule" in next_sentence):
                return True

        # Check for structural indicators of hijacking
        sections = prompt.split("\n\n")
        if len(sections) >= 2:
            # Check if later sections contradict earlier ones
            first_section = sections[0].lower()
            for section in sections[1:]:
                section_lower = section.lower()
                if (("instruction" in first_section or "guideline" in first_section) and
                    ("ignore" in section_lower or "disregard" in section_lower or "forget" in section_lower)):
                    return True

        return False

    def _is_output_secure(self, output: str) -> bool:
        """
        Enhanced security checks on LLM outputs before they are returned.
        Implements advanced detection for data leakage, harmful content, and other security issues.

        Args:
            output (str): The LLM-generated output to be checked

        Returns:
            bool: True if the output passes all security checks, False otherwise
        """
        logger.debug(f"Performing enhanced output security check for Expert '{self.specialty}', Profile '{self.security_profile}'")

        if not output:
            logger.warning("Output security check: Empty output received")
            return False

        # 1. Enhanced PII detection with international formats
        pii_patterns = {
            # US/North American formats
            'email': r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b',
            'us_phone': r'\b(\+?1[-\s.]?)?\(?\d{3}\)?[-\s.]?\d{3}[-\s.]?\d{4}\b',
            'us_ssn': r'\b\d{3}[-\s]?\d{2}[-\s]?\d{4}\b',
            'credit_card': r'\b(?:\d{4}[-\s]?){3}\d{4}\b',

            # International formats
            'intl_phone': r'\b\+\d{1,3}[-\s.]?\d{1,14}\b',
            'uk_phone': r'\b(\+44|0)[-\s]?\d{2,4}[-\s]?\d{3,4}[-\s]?\d{3,4}\b',
            'eu_phone': r'\b(\+[1-9]\d{1,2})[-\s]?\d{2,12}\b',

            # Government IDs
            'passport_num': r'\b[A-Z]{1,2}[-\s]?\d{6,9}\b',
            'drivers_license': r'\b[A-Z0-9]{1,3}[-\s]?\d{2,7}[-\s]?[A-Z0-9]{1,3}\b',
            'national_id': r'\b\d{6,12}[-\s]?\d{2,4}\b',

            # Financial
            'iban': r'\b[A-Z]{2}\d{2}[-\s]?[A-Z0-9]{4}[-\s]?[A-Z0-9]{4}[-\s]?[A-Z0-9]{4}[-\s]?[A-Z0-9]{4}[-\s]?[A-Z0-9]{0,4}\b',
            'swift_bic': r'\b[A-Z]{4}[-\s]?[A-Z]{2}[-\s]?[A-Z0-9]{2}[-\s]?[A-Z0-9]{3}\b',
            'account_number': r'\b\d{8,17}\b',
            'routing_number': r'\b\d{9}\b',

            # Network
            'ip_address': r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b',
            'ipv6_address': r'\b[0-9a-fA-F]{1,4}(:[0-9a-fA-F]{1,4}){7}\b',
            'mac_address': r'\b([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})\b',

            # Location
            'address': r'\b\d+\s+[A-Za-z0-9\s,]+\b(?:street|st|avenue|ave|road|rd|boulevard|blvd|drive|dr|lane|ln|court|ct|plaza|plz|parkway|pkwy)\b',
            'zip_postal': r'\b[A-Z]?\d[A-Z0-9]?[-\s]?\d[A-Z0-9]{2}\b|\b\d{5}(?:[-\s]\d{4})?\b',
            'coordinates': r'\b-?\d{1,3}\.\d{1,15},\s*-?\d{1,3}\.\d{1,15}\b',

            # Health
            'medical_record': r'\b(?:MRN|Medical Record Number):?\s*\d{5,10}\b',
            'health_insurance': r'\b(?:Policy|Group|Member)[-\s]?#:?\s*[A-Z0-9]{5,20}\b',
        }

        # Apply PII detection based on security profile
        if self.security_profile in ['high_security', 'pii_protection', 'confidential']:
            for pii_type, pattern in pii_patterns.items():
                if re.search(pattern, output, re.IGNORECASE):
                    logger.warning(f"Output security check FAILED: Detected potential {pii_type} in output")
                    return False

        # 2. NEW: Entity recognition for names and organizations
        # Simple pattern-based entity detection (a more robust implementation would use NLP)
        entity_patterns = {
            'person_name': r'\b(?:Mr\.|Mrs\.|Ms\.|Dr\.|Prof\.)\s+[A-Z][a-z]+(?:\s+[A-Z][a-z]+)?\b|\b[A-Z][a-z]+\s+[A-Z][a-z]+\b',
            'organization': r'\b[A-Z][a-z]*(?:\s+[A-Z][a-z]*){1,5}(?:\s+(?:Inc\.|Corp\.|LLC|Ltd\.|GmbH|Co\.|Corporation|Company|Limited|International))\b',
        }

        if self.security_profile in ['high_security', 'pii_protection', 'confidential']:
            for entity_type, pattern in entity_patterns.items():
                if re.search(pattern, output, re.IGNORECASE):
                    # For names and organizations, we log but don't automatically block
                    # as these could be common in legitimate outputs
                    logger.info(f"Output security check: Detected potential {entity_type} in output")
                    # In high security mode, we block even potential entity leakage
                    if self.security_profile == 'high_security':
                        logger.warning(f"Output security check FAILED: High security profile detected {entity_type}")
                        return False

        # 3. Enhanced harmful content detection
        harmful_content_patterns = [
            # Violence
            r'\b(?:bomb|explosive|terrorist|terrorism|attack plan|mass casualty|assassination)\b',
            r'\b(?:school shooting|mass shooting|genocide|ethnic cleansing|violent extremism)\b',

            # Cybersecurity exploits
            r'\b(?:hack|exploit|vulnerability|attack vector|zero-day|security hole|backdoor)\b',
            r'\b(?:malware|ransomware|spyware|rootkit|keylogger|botnet|trojan|worm)\b',

            # Illegal activities
            r'\b(?:child abuse|child exploitation|human trafficking|sex trafficking|slavery)\b',
            r'\b(?:drug trafficking|illegal weapons|money laundering|fraud scheme)\b',

            # Self-harm
            r'\b(?:suicide method|how to kill|self-harm technique|suicide instruction)\b',

            # Hate speech indicators
            r'\b(?:racial slur|ethnic slur|hate group|white supremacy|nazi|extremist group)\b',
        ]

        # Always check for harmful content regardless of security profile
        for pattern in harmful_content_patterns:
            if re.search(pattern, output, re.IGNORECASE):
                logger.warning(f"Output security check FAILED: Detected potentially harmful content matching pattern: '{pattern}'")
                return False

        # 4. Enhanced data leakage detection
        if self.security_profile in ['high_security', 'confidential']:
            # Check for potential internal data markers
            internal_data_patterns = [
                # Confidentiality markers
                r'\b(?:confidential|classified|secret|internal[ -]?only|not for distribution)\b',
                r'\b(?:proprietary|do not share|restricted access|privileged communication)\b',
                r'\b(?:internal use|internal document|internal memo|company private)\b',

                # Document classification
                r'\b(?:top secret|secret|confidential|restricted|classified)\b',
                r'\b(?:sensitive but unclassified|for official use only|law enforcement sensitive)\b',

                # Business confidentiality
                r'\b(?:trade secret|business confidential|commercial in confidence)\b',
                r'\b(?:under NDA|covered by non-disclosure|subject to confidentiality agreement)\b',

                # Legal privilege
                r'\b(?:attorney-client privilege|legal privilege|without prejudice)\b',

                # Draft status
                r'\b(?:draft|not final|preliminary|subject to change|not for circulation)\b',
            ]

            for pattern in internal_data_patterns:
                if re.search(pattern, output, re.IGNORECASE):
                    logger.warning(f"Output security check FAILED: Detected potential confidential information matching pattern: '{pattern}'")
                    return False

        # 5. NEW: Check for hallucination indicators
        hallucination_indicators = [
            r"I don't actually (?:know|have|possess)",
            r"I'm (?:making|just making) this up",
            r"I'm not (?:sure|certain) (?:about|of) this",
            r"This (?:might|may) not be (?:accurate|correct|right)",
            r"I (?:might be|may be|could be) (?:wrong|mistaken|incorrect)",
            r"I'm (?:guessing|speculating|hypothesizing)",
            r"I (?:can't|cannot) (?:verify|confirm) this",
            r"This is (?:fictional|made up|not real)",
        ]

        if self.security_profile in ['high_security', 'reliability_focused']:
            for pattern in hallucination_indicators:
                if re.search(pattern, output, re.IGNORECASE):
                    logger.warning(f"Output security check FAILED: Detected potential hallucination indicator: '{pattern}'")
                    return False

        # 6. Enhanced code injection detection
        if self.security_profile in ['high_security', 'code_restricted']:
            code_patterns = [
                # HTML/JavaScript
                r'<script.*?>.*?</script>',
                r'javascript:',
                r'onerror=',
                r'onclick=',
                r'onload=',
                r'onmouseover=',
                r'<iframe.*?>',
                r'<img.*?onerror=',

                # JavaScript functions
                r'eval\(',
                r'setTimeout\(',
                r'setInterval\(',
                r'Function\(',
                r'document\.write\(',
                r'document\.cookie',
                r'document\.location',
                r'window\.location',
                r'localStorage\.',
                r'sessionStorage\.',

                # SQL Injection
                r'(?:SELECT|INSERT|UPDATE|DELETE|DROP|ALTER|UNION).*?(?:FROM|INTO|WHERE|TABLE|DATABASE)',
                r'--.*?(?:SELECT|INSERT|UPDATE|DELETE)',
                r'/\*.*?(?:SELECT|INSERT|UPDATE|DELETE)',

                # Command Injection
                r'`.*?`',  # Backticks for command execution
                r'\$\(.*?\)',  # Command substitution
                r'(?:;|&&|\|\|).*?(?:cat|echo|rm|mv|cp|wget|curl)',

                # File paths
                r'(?:file|https?|ftp)://(?:\.\.)?/',
                r'\.\.(?:/|\\)',  # Directory traversal
            ]

            for pattern in code_patterns:
                if re.search(pattern, output, re.IGNORECASE):
                    logger.warning(f"Output security check FAILED: Detected potential code injection in output matching pattern: '{pattern}'")
                    return False

        # 7. Check output length to prevent resource exhaustion
        max_output_length = 50000  # Reasonable limit
        if len(output) > max_output_length:
            logger.warning(f"Output security check FAILED: Output exceeds maximum length ({len(output)} > {max_output_length})")
            return False

        # 8. NEW: Check for output consistency and coherence
        # This is a simple implementation - a more robust one would use NLP techniques
        if self.security_profile in ['high_security', 'reliability_focused']:
            # Check for repetitive content which might indicate a stuck loop
            words = re.findall(r'\b\w+\b', output.lower())
            if len(words) > 20:  # Only check substantial outputs
                word_counts = Counter(words)
                most_common_words = word_counts.most_common(5)

                # If the most common word appears too frequently, it might indicate repetition
                if most_common_words[0][1] > len(words) * 0.2:  # More than 20% of all words
                    logger.warning(f"Output security check FAILED: Detected potentially repetitive content")
                    return False

                # Check for sentence repetition
                sentences = re.split(r'[.!?]\s+', output)
                if len(sentences) > 5:  # Only check outputs with multiple sentences
                    sentence_counts = Counter(sentences)
                    most_common_sentence = sentence_counts.most_common(1)[0]

                    # If the same sentence appears multiple times, it might indicate a loop
                    if most_common_sentence[1] > 2 and len(most_common_sentence[0].split()) > 5:
                        logger.warning(f"Output security check FAILED: Detected repeated sentences")
                        return False

        # All checks passed
        logger.debug(f"Enhanced output security check PASSED for Expert '{self.specialty}'")
        return True

    def _sanitize_output(self, output: str) -> str:
        """
        Sanitizes output by redacting potential PII and sensitive information
        instead of rejecting it completely.

        Args:
            output (str): The output to sanitize

        Returns:
            str: The sanitized output
        """
        # PII patterns to redact
        pii_patterns = {
            'email': (r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '[EMAIL REDACTED]'),
            'phone': (r'\b(\+\d{1,3}[\s-])?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b', '[PHONE REDACTED]'),
            'ssn': (r'\b\d{3}-\d{2}-\d{4}\b', '[SSN REDACTED]'),
            'credit_card': (r'\b(?:\d{4}[- ]?){3}\d{4}\b', '[CREDIT CARD REDACTED]'),
            'ip_address': (r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b', '[IP ADDRESS REDACTED]'),
            'address': (r'\b\d+\s+[A-Za-z0-9\s,]+\b(?:street|st|avenue|ave|road|rd|boulevard|blvd|drive|dr|lane|ln|court|ct|plaza|plz|parkway|pkwy)\b', '[ADDRESS REDACTED]'),
        }

        sanitized = output

        # Apply redactions
        for pii_type, (pattern, replacement) in pii_patterns.items():
            sanitized = re.sub(pattern, replacement, sanitized, flags=re.IGNORECASE)

        # Add a notice if redactions were made
        if sanitized != output:
            sanitized += "\n\n[NOTICE: This output has been automatically sanitized to remove potential sensitive information.]"

        return sanitized


    # TODO: Implement methods for tool validation, secure communication handling, etc.

    def _format_with_inputs(self, text: str, inputs: Dict[str, Any]) -> str:
        """
        Formats a string by replacing template variables with values from inputs.
        Template variables are in the format {variable_name}.

        Args:
            text (str): The text containing template variables
            inputs (Dict[str, Any]): Dictionary of input values to use for formatting

        Returns:
            str: The formatted text with template variables replaced
        """
        if not text or not inputs:
            return text

        # Create a copy of the text to avoid modifying the original
        formatted_text = text

        # Replace each template variable with its corresponding value
        for key, value in inputs.items():
            placeholder = "{" + key + "}"
            if placeholder in formatted_text:
                # Convert value to string if it's not already
                str_value = str(value) if not isinstance(value, str) else value
                formatted_text = formatted_text.replace(placeholder, str_value)

        return formatted_text
