# tbh_secure_agents/agent.py
# Author: Saish (TBH.AI)

"""
Defines the core Agent class for the TBH Secure Agents framework.
Agents will encapsulate roles, goals, tools, and security contexts,
utilizing Google Gemini as the LLM.
"""

import google.generativeai as genai
import os
import logging # Import logging
from typing import Optional, List, Any

# Get a logger for this module
logger = logging.getLogger(__name__)

# Configure the Gemini API key securely
# The library automatically looks for the GOOGLE_API_KEY environment variable.
# Ensure this variable is set in your environment.
# Example: export GOOGLE_API_KEY='YOUR_API_KEY'
# Configuration will now happen within Agent __init__ if key is provided

# Removed duplicate class definition here (already done)

class Agent:
    """
    Represents an autonomous agent within the TBH Secure Agents framework.

    Attributes:
        role (str): The role of the agent (e.g., 'Security Analyst').
        goal (str): The primary objective of the agent.
        backstory (str, optional): A description of the agent's background.
        llm_model_name (str): The specific Gemini model to use (e.g., 'gemini-pro'). Defaults to 'gemini-pro'.
        tools (List[Any], optional): A list of tools available to the agent.
        security_profile (str, optional): Defines the security constraints and capabilities. Defaults to 'default'.
        # Add other relevant attributes like memory, max_iterations, etc.
    """
    def __init__(self,
                 role: str,
                 goal: str,
                 backstory: Optional[str] = None,
                 llm_model_name: str = 'gemini-2.0-flash-lite', # Updated default model name per user request
                 tools: Optional[List[Any]] = None,
                 security_profile: str = 'default',
                 api_key: Optional[str] = None, # Add api_key parameter
                 **kwargs):
        self.role = role
        self.goal = goal
        self.backstory = backstory
        self.llm_model_name = llm_model_name
        self.tools = tools or []
        self.security_profile = security_profile
        self.llm: Optional[genai.GenerativeModel] = None

        # --- Initialize Gemini LLM ---
        # Prioritize explicitly passed API key, fall back to environment variable
        effective_api_key = api_key or os.getenv("GOOGLE_API_KEY")

        if effective_api_key:
            try:
                # Configure the API key (Note: genai.configure is global)
                # In a multi-key scenario, this might need a more complex setup
                genai.configure(api_key=effective_api_key)
                logger.info("Gemini API configured.") # Use logger

                # Create the model instance
                # TODO: Add generation_config and safety_settings based on security_profile
                self.llm = genai.GenerativeModel(self.llm_model_name)
                logger.info(f"Agent '{self.role}' initialized with Gemini model '{self.llm_model_name}' and security profile '{self.security_profile}'.") # Use logger

            except Exception as e:
                logger.error(f"Error initializing Gemini model for agent '{self.role}': {e}", exc_info=True) # Use logger, add traceback
                self.llm = None # Ensure llm is None if initialization fails
        else:
             logger.warning(f"Agent '{self.role}' initialized WITHOUT a functional LLM (No API key found/provided).") # Use logger

        # Initialize other components like memory, potentially based on kwargs or profile
        self.memory = None # Placeholder for agent memory/chat history
        # TODO: Implement actual memory initialization (e.g., based on kwargs or a Memory class)
        logger.debug(f"Agent '{self.role}' memory initialized (placeholder).")


    def execute_task(self, task_description: str, context: Optional[str] = None) -> str:
        """
        Executes a given task description using the configured Gemini LLM.
        This method will involve constructing a prompt, interacting with the LLM,
        potentially using tools (future implementation), and applying security checks.

        Args:
            task_description (str): The description of the task to execute.
            context (Optional[str]): Relevant context from previous tasks or external data.

        Returns:
            str: The result generated by the LLM or an error message.
        """
        if not self.llm:
            logger.error(f"Agent '{self.role}' cannot execute task: LLM not initialized.") # Use logger
            return f"Error: Agent '{self.role}' cannot execute task. LLM not initialized (check API key and configuration)."

        logger.info(f"Agent '{self.role}' starting task execution: {task_description[:100]}...") # Use logger

        # --- Prompt Engineering ---
        # Construct a prompt incorporating role, goal, task, context, and security constraints.
        # This is a crucial area for security: ensure prompts don't enable injection attacks
        # and guide the LLM towards secure and relevant outputs.
        prompt = f"You are {self.role}. Your goal is {self.goal}."
        if self.backstory:
            prompt += f" Your backstory is: {self.backstory}."
        if context:
            prompt += f"\n\nRelevant context:\n{context}"
        prompt += f"\n\nCurrent Task: {task_description}"
        prompt += f"\n\nPlease provide the result for this task, keeping in mind your role and goal."
        # TODO: Add specific instructions based on security_profile (e.g., "Do not reveal confidential data", "Sanitize output")
        # TODO: Add specific instructions for tool usage format if tools are implemented

        # --- Security Check (Pre-LLM) ---
        # Placeholder call, actual logic is in _is_prompt_secure
        if not self._is_prompt_secure(prompt):
             logger.error(f"Prompt failed pre-execution security check for agent '{self.role}'. Task aborted.") # Use logger
             return f"Error: Prompt failed pre-execution security check for agent '{self.role}'."

        # --- LLM Interaction ---
        # Basic retry logic implemented below
        max_retries = 1 # Example: Allow 1 retry
        attempts = 0
        llm_output = None # Initialize output variable

        while attempts <= max_retries:
            attempts += 1
            try:
                logger.debug(f"LLM interaction attempt {attempts} for agent '{self.role}'.")
                # TODO: Implement actual use of chat history (self.memory) when generating content
                # Example: history = self.memory.get_history() ... self.llm.generate_content(prompt, history=history)
                # TODO: Pass configured generation_config/safety_settings to generate_content if implemented in __init__
                response = self.llm.generate_content(prompt)

                # --- Security Check (Post-LLM) ---
                # Placeholder call, actual logic is in _is_output_secure
                llm_output = response.text # Accessing the text part of the response
                if not self._is_output_secure(llm_output):
                    # Handle insecure output (e.g., log, sanitize, return error)
                    logger.warning(f"LLM output for agent '{self.role}' failed post-execution security check. Output rejected.")
                    # TODO: Implement actual sanitization or specific error handling based on policy
                    return f"Error: Agent '{self.role}' generated an insecure response." # Or return sanitized version

                # If successful, break the loop
                logger.info(f"Agent '{self.role}' successfully executed task on attempt {attempts}.") # Use logger
                break # Exit the while loop on success

            except Exception as e:
                # Basic error logging implemented
                logger.error(f"Attempt {attempts}: Error during LLM interaction for agent '{self.role}': {e}", exc_info=(attempts > max_retries))
                if attempts > max_retries:
                    # If all retries failed, return an error
                    # TODO: Implement more specific error handling/reporting
                    return f"Error: Agent '{self.role}' failed to execute task after {attempts} attempts due to LLM error: {e}"
                # Optional: Add delay before retry
                # import time
                # time.sleep(1)
                # Continue to the next iteration (retry)

        # Return the successful output, or an error if the loop finished without success (shouldn't happen with current logic but good practice)
        if llm_output is not None:
             return llm_output
        else:
             # This path indicates an issue with the loop logic or unexpected state
             logger.error(f"Agent '{self.role}' finished execution loop unexpectedly without success or final error.")
             return f"Error: Agent '{self.role}' failed task execution unexpectedly."


    # --- Placeholder Security Methods ---
    # These need significant implementation based on specific security requirements.

    def _is_prompt_secure(self, prompt: str) -> bool:
        """Placeholder for pre-LLM prompt security checks. Needs implementation."""
        logger.debug(f"Performing prompt security check for Agent '{self.role}', Profile '{self.security_profile}'")
        # TODO: Implement actual security logic here based on self.security_profile (e.g., check for blacklisted patterns, enforce length limits)
        is_secure = True # Defaulting to secure for now
        if not is_secure:
            logger.warning(f"Prompt security check FAILED for Agent '{self.role}'.")
        return is_secure

    def _is_output_secure(self, output: str) -> bool:
        """Placeholder for post-LLM output security checks. Needs implementation."""
        logger.debug(f"Performing output security check for Agent '{self.role}', Profile '{self.security_profile}'")
        # TODO: Implement actual security logic here based on self.security_profile (e.g., scan for PII, secrets, harmful content)
        is_secure = True # Defaulting to secure for now
        if not is_secure:
            logger.warning(f"Output security check FAILED for Agent '{self.role}'.")
        return is_secure


    # TODO: Implement methods for tool validation, secure communication handling, etc.
